### ISSUE TITLE
Alignment issues on iPhone x

### ISSUE THREAD

**Issue by michspp** [OatmealDome/DolphiniOS-Issue-Tracker#10]
**Describe the issue**
DolphiniOS alignment it's not correct on iPhone X, the game screen overlap the controls.

Is there any way to configure Dolphinios to occupy the area marked in the image on the iphone x so that looks better distributed and clean in vertical mode?
 Thanks

**How to reproduce**
Load a game and try to play in vertical mode.

For example: 
1. Open Any Game
2. Set the device orientation vertical 
3. See how the game screen section overlay controls and set the position on a middle of the device screen.

**Expected result**
Adjust correctly the distribution of space, set the game screen up at the top of screen and controls moveable so each player can adjust every button to a desired position and change the size of each button.

**Device information**
 - Device [iPhone X]
 - OS [iOS 12.4]
 - Jailbreak [unc0ver]
 - DolphiniOS version (go to the Settings tab) [v1.0.7]

**Additional information**
Please add a configuration section that allow move the controller buttons and set the position of the screen play freely.

THANK YOU SO MUCH FOR THIS AMAZING WORK!!!! The emulation was fine and pretty smooth. 

![FC72F0A5-9C41-4E0D-9973-CA8659A7A458](https://user-images.githubusercontent.com/41181878/70955934-715ae700-2040-11ea-8a58-c64822a1e3d4.jpeg)

label:bug

**Comment by OatmealDome** [comment]
Fixed in 1.1.0.
