### ISSUE TITLE
Francesca pianta rapidly moving back and forth during cutscene in Paper Mario TTYD

### ISSUE THREAD

**Issue by Zekek11** [OatmealDome/DolphiniOS-Issue-Tracker#101]
In chapter 5 of Paper Mario The Thousand Year Door, there is a cutscene after you defeat Cortez. Before the cutscene, you blow a hole in the wall on top of a ledge. Blowing the hole in the wall triggers the cutscene. In this cutscene, one toad will enter the hole followed by another toad. After this, two piñatas will attempt to enter. When this happens, though, the blue pianta will reach the top of the ledge and stop, normally. However, the yellow pianta does this thing where she rapidly moves back and forth. This stops the game, and the pianta will move back and forth forever until you turn the game off. I tried restarting and trying again multiple times but it happens every time.

**How to reproduce**

1. Open Paper Mario, The Thousand Year Door for GameCube.
2. Defat Cortez in chapter 5.
3. Go into the room to the left of Cortez’s boat.
4. Blow a hole in the wall on top of the ledge with the crack. 
5. Wait for the cutscene to play.
6. See Francesca pianta start to rapidly move back and forth.
7. See game freeze.

**Expected result**
Francesca pianta rapidly moves back and forth forever and the game Freezes. 

**Device information**
 - IPhone Xs Max
 - iOS 13.4.1
 - No Jailbreak
 - DolphiniOS version 2.2.2 (1) (NJB)

**Comment by OatmealDome** [comment]
This is probably an issue carried over from the Android version of Dolphin - TTYD is buggy there too.

You can try to disable some JIT things in Settings -> Debug -> JIT. One of them might help bypass the issue.

**Comment by Zekek11** [comment]
Yep, I just had to select paired disabled and now that whole part runs at 60 FPS. Thanks a ton
