### ISSUE TITLE
Immediate XFB=true makes DiOS crash

### ISSUE THREAD

**Issue by N-Games** [OatmealDome/DolphiniOS-Issue-Tracker#103]
**Describe the issue**
The title says it all

**How to reproduce**
Immediate XFB=true in GFX.ini

**Expected result**
Games running with fickering?

**Device information**
 - Device [iPhone 6]
 - OS [e.g. iOS 12.4.7]
 - Jailbreak [checkra1n]
 - DolphiniOS version Latest Public Build

**Comment by OatmealDome** [comment]
Works for me if I enable it in the settings menu (Settings -> Graphics -> Hacks -> Immediately Present XFB).

Here's what is appended to GFX.ini when I enable it:
```
[Hacks]
ImmediateXFBEnable = True
```

Also, your device is unsupported.
