### ISSUE TITLE
Multi-touch not working correctly in landscape mode.

### ISSUE THREAD

**Issue by sagar-13** [OatmealDome/DolphiniOS-Issue-Tracker#11]
**Describe the issue**
Was playing Crash Nitro Kart. In portrait mode, turning and accelerating is flawless and can be done at the same time however, in landscape mode, when moving the left stick while holding the A button (for acceleration), the acceleration stops until the left stick stops moving. 

**How to reproduce**
Describe how to reproduce the issue.

For example: 
1. Open Crash Nitro Kart or perhaps another racing game.
2. Try to accelerate while turning specifically using the left stick while holding the A button. 

**Expected result**
What did you expect to happen?
Should work like it does in portrait mode. 

**Device information**
 - iPhone XR
 - iOS 12.4
 - Unc0ver
 - DolphiniOS version 1.08

**Additional information**
Really appreciate the work on this project. It's running great.

[video_multitouch_issue.zip](https://github.com/OatmealDome/DolphiniOS-Issue-Tracker/files/3971815/video_multitouch_issue.zip)

**Comment by sagar-13** [comment]
Video of problem:

**Comment by OatmealDome** [comment]
I can't seem to open the video. QuickTime is giving me an error.

**Comment by sagar-13** [comment]
[720p.mp4.zip](https://github.com/OatmealDome/DolphiniOS-Issue-Tracker/files/3981343/720p.mp4.zip)

Converted to mp4. Hopefully this helps.

**Comment by OatmealDome** [comment]
Works, thanks.
