### ISSUE TITLE
Super Paper Mario Freeze

### ISSUE THREAD

**Issue by boy13epic** [OatmealDome/DolphiniOS-Issue-Tracker#112]
**Describe the issue**
so,if I load a save file,the game just freezes

**How to reproduce**
1.open Super Paper Mario
2.Load a save file
3.The game just freezes

**Expected result**
load the game

**Device information**
 - Device iPad 6
 - OS 13.3.1
 - Jailbreak Unc0ver
 - DolphiniOS version 3.0.0

**Comment by OatmealDome** [comment]
Don't use NKit for Super Paper Mario. Redump your game and use the original dump.
