### ISSUE TITLE
Dpad not rotating

### ISSUE THREAD

**Issue by Stardust-kyun** [OatmealDome/DolphiniOS-Issue-Tracker#12]
For Wii games, the only control scheme is a Wii remote and nunchuck. For games that require for the remote to be flipped sideways, this leads to the dpad being flipped: up is right, down is left, etc.

To reproduce just open up a game like Super Paper Mario and try to move as you expect it to.

I expected for the control scheme to change depending on the game's required controls.

 - iPhone 7
 - iOS 13.2.3
 - jailbroken with checkra1n
 - DolphiniOS version 1.0.8

Here it is on video:
https://streamable.com/sjvf3

**Comment by OatmealDome** [comment]
This is now in beta testing with Patrons.

**Comment by OatmealDome** [comment]
Fixed in 1.1.0.
