### ISSUE TITLE
RVZ files are not selectable in add menu.

### ISSUE THREAD

**Issue by nathanielcwm** [OatmealDome/DolphiniOS-Issue-Tracker#125]
**Describe the issue**
Games which are compressed with rvz compression are not selectable in the add games menu.

**How to reproduce**
1. Compress a game into rvz on Dolphin on a PC
2. Transfer the file to your iOS device
3. Attempt to add it to DolphiniOS
4. Observe that the file is greyed out.

**Expected result**
File isn't greyed out and is selectable

**Device information**
 - Device: iPad Pro 9.7
 - OS: 13.5
 - Jailbreak method: Unc0ver
 - DolphiniOS version: 3.0.0  
 - Emulated game: 

**Additional information**

**Comment by nathanielcwm** [comment]
I didn't see it mentioned on twitter.

**Comment by Simonx22** [comment]
3.1.0 is now available. https://oatmealdome.me/blog/dolphinios-ver-3-1-0/
