### ISSUE TITLE
Installing wads directly to the nand/title from file browser 

### ISSUE THREAD

**Issue by Alexsky14** [OatmealDome/DolphiniOS-Issue-Tracker#126]
Being able to install “not import” wads files to the title/ nand like
on pc and android.
![E874328B-0288-4F48-BF36-4DD9AD5CDB76](https://user-images.githubusercontent.com/59045453/90987862-d82b8b00-e553-11ea-8d38-a9ec60adc13d.jpeg)

**Comment by OatmealDome** [comment]
Press and hold on a title in the games list, then press "Install to the NAND".
