### ISSUE TITLE
An option to select or change the audio engine like on pc

### ISSUE THREAD

**Issue by Alexsky14** [OatmealDome/DolphiniOS-Issue-Tracker#128]
**Audio engine emulator selection**
I Would like to add an option to change the audio engine or audio controls.

![D35CE649-2FC1-4C7B-A61B-264B0332EDC8](https://user-images.githubusercontent.com/59045453/91120968-7145c900-e65c-11ea-855e-4715b764a238.png)

**Comment by OatmealDome** [comment]
DSP LLE does not function on phones or tablets. It is only compatible with Intel CPUs.

In addition, the only audio backend available is CoreAudio.
