### ISSUE TITLE
Nkit detection

### ISSUE THREAD

**Issue by JackFusion07** [OatmealDome/DolphiniOS-Issue-Tracker#136]
**Describe the feature you'd like**
If it's at all possible, when loading up games, if DiOS sees it's loading as an nkit.iso file, there should be a pop-up stating that nkit.iso files tend to cause more problems than fix, and that they should redump their game or convert it to a different file type (which can also serve as a reminder that DiOS doesn't support piracy since a majority of nkit.iso is downloaded. 😔)

Thank you bupoatmeal#9038 for the idea.

**Comment by OatmealDome** [comment]
Isn't this already a thing?

![image](https://user-images.githubusercontent.com/11504941/99126362-06a98700-25d4-11eb-86d7-d6dbb3bf9ad6.png)

**Comment by JackFusion07** [comment]
god damn it
