### ISSUE TITLE
[3.1.1 - 3.2.0B1] not able to boot any games with phycic paper version

### ISSUE THREAD

**Issue by Spidy123222** [OatmealDome/DolphiniOS-Issue-Tracker#137]
I cannot boot my games at all. I tried turning off fastmem and changing to intepiter and got nothing. I removed config to go to default thinking it might broken the original.

**How to reproduce**
Have a A11 device on bios 13.4.1 with dolphin for IOS 3.1.1 uni.

Sideload with altstore and accept entitlement. Enter dolphin and have any setting and boot any game.

**Expected result**
I expected to have same or better performance from updating dios to 3.1.1 from 3.0.0

**Device information**

 - Device: iPhone 8+ 64gb Verizon
 - OS: iOS 13.4.1
 - Jailbreak method: none
 - DolphiniOS version:  3.1.1
 - Emulated game: all of above. What is in my list of games.

**Additional information**
I have a short video of trying to boot a game and have crash log.

Video: https://cdn.discordapp.com/attachments/595239075842228225/777112683702386688/video0.mov

Log: https://drive.google.com/file/d/1Q_V_P6N_Hp1wMkK32NdNiNwiku3P6LdJ/view?usp=drivesdk

**Comment by Spidy123222** [comment]
I reinstalled again and removed config folder still nothing.

**Comment by EGNL** [comment]
I’m having the same issue, version 3.1.0 and 3.0.0 just work fine but when i launch any game in version 3.1.1 of DolphiniOS, it just crashes. I have an iPad Air 3 on iOS 13.3.1 (Not Jailbroken).

**Comment by escape1** [comment]
Can confirm this with my iPhone 11 

ios : 13.1.3

Dolphinios version : 3.1.1 (129)

Jailbrake state : Non Jb

**Comment by Spidy123222** [comment]
I have updated to latest altstore and server and reinstalled there's no change to story.

**Comment by Spidy123222** [comment]
I tried latest beta (3.2.0B1) I'm not able to boot still because of a error that exits the app. ![image](https://user-images.githubusercontent.com/64176728/101412111-e600e400-3896-11eb-95c4-0894947fb35c.png)

I got a log and I checked it and I saw invalid access message.
![image](https://user-images.githubusercontent.com/64176728/101412168-fb760e00-3896-11eb-917a-a9bc60ad53f2.jpeg)

Log: https://drive.google.com/file/d/1LonkBOUwOkb2QPvtChlAFI0k25-Ls_2w/view?usp=drivesdk

**Comment by Spidy123222** [comment]
@OatmealDome is there a known fix that will come up in a beta?

**Comment by Spidy123222** [comment]
This is a altstore issue also ima close issue
