### ISSUE TITLE
GPL-2.0 Compliance

### ISSUE THREAD

**Issue by Drakal** [OatmealDome/DolphiniOS-Issue-Tracker#14]
Self explanatory.

**Comment by OatmealDome** [comment]
[Already compliant.](https://github.com/OatmealDome/dolphin/tree/ios-jb)

**Comment by thejsa** [comment]
> Already compliant.

Is this still the case? That fork doesn’t seem to have been updated for over a month, but new Patreeon builds have been published as recently as last week.
