### ISSUE TITLE
Games with “Controller Map Overlap” receive no input

### ISSUE THREAD

**Issue by goob47** [OatmealDome/DolphiniOS-Issue-Tracker#15]
**Describe the issue**
Games like Goldeneye 007 that have controller map overlap (as shown on the wiki page here: https://wiki.dolphin-emu.org/index.php?title=GoldenEye_007) do not receive any input because the GCPadNew.ini has controller profiles in it. When they are removed, wiimote and nunchuck controls function normally.

**How to reproduce**
Launch Goldeneye 007 or similar game and try any form of button inputs.

**Expected result**
Normal wiimote and nunchuck functionality.

**Device information**
 - Device: iPhone X
 - OS: iOS 12.4
 - Jailbreak: checkra1n
 - DolphiniOS version: 1.0.8

**Additional information**
N/A

**Comment by OatmealDome** [comment]
Fixed in 2.0.0.
