### ISSUE TITLE
A button double presses automatically

### ISSUE THREAD

**Issue by WhenCornAttacks** [OatmealDome/DolphiniOS-Issue-Tracker#16]
I’m playing Battle For Bikini Bottom and it seems like sometimes when I press A, it goes straight into a double jump, as if the button is being pressed rapidly. 

**How to reproduce**
This issue occurs throughout the entire game, from the very start. 

**Expected result**
Usually, you can double jump just by pressing A and pressing A again in midair, which plays a different animation than a single jump. But with this bug, sometimes the double jump is done with a single press.  

**Device information**
 - iPhone 7
 - iOS 13.2
 - checkra1n 
 - DolphiniOS v1.0.7

**Comment by OatmealDome** [comment]
Should be fixed in 2.0.0? Let me know if it's still an issue.
