### ISSUE TITLE
Sonic adventure 2 battle black textures

### ISSUE THREAD

**Issue by mmdgamer** [OatmealDome/DolphiniOS-Issue-Tracker#168]
**Describe the issue**

I’m on ios 15.0.1 using altstore beta (3.2.0b2) and whenever I try to play sonic adventure 2 battle it works with good performance but all the textures are broken and it seems like they are covered in something black because some textures flash for an instant showing how the actual texture is supposed to look like so the textures themselves don’t seem to be broken or not working

**How to reproduce**

Probably something to do with vulkan because i tried with OpenGL and even though it’s really slow the textures were there 

**Expected result**

The game to have working textures like some old youtube videos of the emulator
**Device information**

 - Device: iphone 12 pro
 - OS: ios 15.0.1
 - Jailbreak method: non-jailbroken
 - DolphiniOS version:  3.2.0b2
 - Emulated game: sonic adventure 2 battle

**Additional information**

**Comment by HStephens05** [comment]
This can be fixed by installing the most recent build of DolphiniOS posted here: https://github.com/OatmealDome/dolphin/releases/tag/3.2.0b2-194

**Comment by mmdgamer** [comment]
Thank you so much it works now
