### ISSUE TITLE
Xbox Series X/S Controller Joysticks & Triggers not working

### ISSUE THREAD

**Issue by SomeoneOutThereSomewhere** [OatmealDome/DolphiniOS-Issue-Tracker#174]
Using the Xbox Series X/S controller, since the last controller update (Check device information) it won't recognize the joystick inputs & LT, RT

**How to reproduce:**
Connect the Xbox Series X/S Controller to phone via Bluetooth > Try changing/adding controller inputs/playing any game with controller

**Expected result:**
Properly working inputs

**Device information:**
 - Device: Samsung Galaxy S20 FE 5G
 - OS: Android 11
 - Controller Ver. 5.11.3118.0 (Check Xbox Accessories App)
 - Version: Any, used ver. 5.0-15445
 - Emulated game: Any game

**Comment by OatmealDome** [comment]
Hi!

This is the issue tracker for DolphiniOS, a version of Dolphin for iOS devices. Since you appear to be using an Android device, you should seek support on [the Dolphin forums](https://forums.dolphin-emu.org/) instead.

**Comment by SomeoneOutThereSomewhere** [comment]
Oh sorry! I'm new here & was wondering
