### ISSUE TITLE
[Bug] Non-Jailbroken DolphiniOS Crashing after using JIT, both Beta and Non-Beta

### ISSUE THREAD

**Issue by ShoweringStars** [OatmealDome/DolphiniOS-Issue-Tracker#178]
**Describe the issue**
The problem is that whenever I try to open a game after it passing a single day, it won’t let me in.

**How to reproduce**

All you have to do to reproduce the issue is to open a game after 1 day and it just breaks, even with JIT.

**Expected result**

What I expected is to load into the game like regular and be able to play.
**Device information**

 - Device: iPhone 12
 - OS: iOS 15.3.1
 - Jailbreak method: None
 - DolphiniOS version:  3.1.1 (Stable), 3.2.0b2 (Public Beta)
 - Emulated game: Any

**Additional information**

I tried multiple ways of using JIT, including the workaround and JIT streamer. For some reason, after a single day the app won’t let me play any games anymore.

**Comment by ShoweringStars** [comment]
whoops, this issue wasn’t done yet but GitHub automatically posted it somehow

**Comment by ShoweringStars** [comment]
should be good to go now

**Comment by Spidy123222** [comment]
> **Describe the issue** The problem is that whenever I try to open a game after it passing a single day, it won’t let me in.
> 
> **How to reproduce**
> 
> All you have to do to reproduce the issue is to open a game after 1 day and it just breaks, even with JIT.
> 
> **Expected result**
> 
> What I expected is to load into the game like regular and be able to play. **Device information**
> 
> * Device: iPhone 12
> * OS: iOS 15.3.1
> * Jailbreak method: None
> * DolphiniOS version:  3.1.1 (Stable), 3.2.0b2 (Public Beta)
> * Emulated game: Any
> 
> **Additional information**
> 
> I tried multiple ways of using JIT, including the workaround and JIT streamer. For some reason, after a single day the app won’t let me play any games anymore.

None of the jit workarounds are permanent you have to reactivate your use again.

**Comment by ShoweringStars** [comment]
Actually, I’ve been redoing the JIT workarounds over and over and still no sign of fix. Do you think it’s a problem with the device and not the app itself?

**Comment by Spidy123222** [comment]
> Actually, I’ve been redoing the JIT workarounds over and over and still no sign of fix. Do you think it’s a problem with the device and not the app itself?

Have you used this beta? https://github.com/OatmealDome/dolphin/releases/tag/3.2.0b2-204

**Comment by ShoweringStars** [comment]
Hmm, haven’t tried it yet, I’ll see if it works

**Comment by ShoweringStars** [comment]
It seems to be working fine, but I’ll see if it works tomorrow.

**Comment by ShoweringStars** [comment]
I’ll close the issue for now and reopen it later if there’s a problem.

**Comment by ShoweringStars** [comment]
Seems to be working after 2 days! Although, I really hope a version comes out that solves this issue for me… guess we’ll have to wait and see
