### ISSUE TITLE
Cannot change discs

### ISSUE THREAD

**Issue by OatmealDome** [OatmealDome/DolphiniOS-Issue-Tracker#18]
**Describe the feature you'd like**
A 'change disc' option should be added like on other versions of Dolphin.

**Device information**
 - iPhone X
 - iOS 13.3
 - checkra1n
 - 1.1.2 (1)

**Comment by Aatoz** [comment]
Yes, please!!

**Comment by OatmealDome** [comment]
Fixed in latest Patreon, public release soon.
