### ISSUE TITLE
Games crash mid game

### ISSUE THREAD

**Issue by thatgirlsarah** [OatmealDome/DolphiniOS-Issue-Tracker#182]
**Describe the issue**

Any game I open gives me an error mid-game and makes the game crash(see screenshots)

**How to reproduce**

1. Open a game
2. Play for a few seconds
3. Error pops up, close it and the game will crash
**Expected result**

For my games to play with no issues
**Device information**

 - Device: iPhone 12 Pro
 - OS: iOS 15.5
 - Jailbreak method: N/A used AltStore
 - DolphiniOS version:  3.2.0
 - Emulated game: Mostly happening
 with Mario Kart Wii and Kirby’s Return to Dream Land but it does this with Shadow the Hedgehog and Luigi’s Mansion too.

**Additional information**

![75DA18A4-F09C-4E37-A41D-476E10DAFA34](https://user-images.githubusercontent.com/68525892/169952458-29d8dc01-cea6-4de8-87e0-ac2e6a47eda0.png)
![5BA2C2EF-43E8-4993-A695-8C6B59E50A08](https://user-images.githubusercontent.com/68525892/169952460-2015b062-1210-4ed2-b5b2-15bb2aa0c5e0.png)

**Comment by Simonx22** [comment]
Please try disabling Dual Core: Settings -> Config -> General -> turn off "Enable Dual Core.

**Comment by thatgirlsarah** [comment]
I didn't realize it was that simple😅 Thanks for the help!
