### ISSUE TITLE
DolphiniOS crashes when game starts

### ISSUE THREAD

**Issue by GizmoHD4Life** [OatmealDome/DolphiniOS-Issue-Tracker#190]
in currently on ios 16. trying to use mario kart wii.wbfs. and when i start the game, dolphinios immediadley crashes. i already disabled fastmem but it doesn't change anything. it also turns on automatically after restart. and enabling jit also changes nothing

install mario kart wii from vinns lair
launch dolphin
add game to dolphin
use pc to enable jit
start game

Game is supposed to Launch successfully.

 - Device: iPhone 12
 - OS: 16
 - Jailbreak method: none
 - DolphiniOS version:  3.2.0
 - Emulated game: Mario kart wii

**Comment by JJTech0130** [comment]
No piracy

**Comment by OatmealDome** [comment]
We do not support piracy.
