### ISSUE TITLE
Double tap gesture recognizer conflicts with uibutton tapgesturerecognizers

### ISSUE THREAD

**Issue by goob47** [OatmealDome/DolphiniOS-Issue-Tracker#21]
**Describe the issue**
The UITapGestureRecognizer called tap_recognizer in EmulationViewController.swift conflicts with the gesture recognizer in the controller buttons. This causes lag when pressing two buttons at the same time and can result in stuck buttons. I think that to avoid these gesture conflicts in the future, a dedicated menu button should be created rather than a tap gesture. 
 
**How to reproduce**
Press A and B at the same time on the touch screen during emulation.

**Device information**
 - Device: iPhone X
 - OS: 12.4
 - Jailbreak: unc0ver
 - DolphiniOS Version: 1.1.2 (1) - Patreon

**Additional information**
Should be an easy fix, just might be annoying to add to every view and find a good place for it. I'll try to think of some creative solutions.

**Comment by OatmealDome** [comment]
Fixed in 2.0.0.
