### ISSUE TITLE
Major frame drops occur in increments

### ISSUE THREAD

**Issue by gerbil-snot** [OatmealDome/DolphiniOS-Issue-Tracker#23]
**Describe the issue**
Frame drops occur in increments when playing any game for 10-15 minutes. It will happen during room transitions, when more aspects are loaded, or normally, at random times preforming different actions. The game will appear to freeze and after sitting for 1-2 minutes start very slowly advancing frame by frame until it gets back up to normal speed (after 5-10 minutes)

**How to reproduce**
Play a game normally for at least 20 minutes, the bug has come up every time I play for long periods. 

Games the bug has appeared (all the games I’ve played): 
1. [GC] Zelda Wind Waker
2. [Wii] Mario Party 8
3. [GC] Zelda Twilight Princess

**Device information**
 - iPhone Xs Max 
 - IOS 12.4
 - unc0ver Jailbreak v3.7.0~b3
 - DolphiniOS version 1.1.2 (1)

**Additional information**
Some times the game won’t always continue at full speed after the bug has stopped, it will run around 25 fps and continue that way until you restart the emulation. Also, if you continue playing after waiting out the bug, it will occur again at the same 10-15 minute increments.

**Comment by brand175** [comment]
Same 👀

**Comment by OatmealDome** [comment]
Should be fixed now. Please let me know if it happens again (though make sure it's not because your phone is thermal throttling).
