### ISSUE TITLE
App is “crashing” when the user force closes the app. 

### ISSUE THREAD

**Issue by gerbil-snot** [OatmealDome/DolphiniOS-Issue-Tracker#24]
**Describe the issue**
The tweak CrashReporter is wrongly reporting DolphiniOS crashing every time I force close the app. Crash log is under Additional Information. 

**How to reproduce**
1. Download the tweak CrashReporter using the repo https://cokepokes.github.io/
2. Open DolphiniOS.
3. Open the app switcher screen and force close DolphiniOS, it tends to happen more often when playing a game. 
4. CrashReporter will send you a notification that DolphiniOS has crashed with no suspects. 

**Expected result**
CrashReporter should not report the app as crashing. 

**Device information**
 - iPhone Xs Max 
 - iOS 12.4
 - unc0ver v3.7.0~b3
 - DolphiniOS v1.1.2 (1)

**Additional information**
This is definitely not a big issue, but I figured I’d bring it to attention anyway. The crash log can be found here: https://pastebin.com/K5MPnWTA

**Comment by OatmealDome** [comment]
Partially fixed in 2.0.0, but should be completely fixed in 2.1.0.

**Comment by OatmealDome** [comment]
Assumed fixed
