### ISSUE TITLE
Touchscreen Port 2 *Bug*

### ISSUE THREAD

**Issue by brand175** [OatmealDome/DolphiniOS-Issue-Tracker#25]
**Describe the issue**
Touchscreen controls shows but doesn't work.

**How to reproduce**
Set touchscreen controls to Port 2 and use a MFi controller for Port 1

**Expected result**
Port 2 touchscreen controls don't works

**Device information**
 - Device "Any"
 - OS 12.4
 - Jailbreak "Any"
 - DolphiniOS version (2.0 Patreon build)

**Additional information**
Going to the GCPadNew.ini and changing Android/1/Touchscreen under GCPad2 to Android/0/Touchscreen fixes this issue. /1/Touchscreen doesn't exist because the iPhone and iPad doesn't have 2 touchscreens.

**Comment by OatmealDome** [comment]
Should be fixed now.
