### ISSUE TITLE
DolphinIOS fullscreen iPhone X 

### ISSUE THREAD

**Issue by theomajeed** [OatmealDome/DolphiniOS-Issue-Tracker#26]
How do I make Dolphin emulator full screen on iPhone X?

Using the GFX.ini or the Dolphin.ini
**Device information**
 - Device [e.g. iPhone X]
 - OS [e.g. iOS 13.1]
 - Jailbreak [e.g. checkra1n]
 - DolphiniOS version (go to the Settings tab) [e.g. v1.0.5]

**Additional information**
Add any other information here that does not fit into the above sections.

**Comment by theomajeed** [comment]
How do I make fullscreen on iPhone X, covering the whole screen?

**Comment by OatmealDome** [comment]
Isn't it already full screen?

**Comment by theomajeed** [comment]
No it’s not.
Isn’t there a way to make it full screen?

**Comment by Simonx22** [comment]
Can you please describe how it isn't full screen already? Maybe attach screenshots or something

**Comment by theomajeed** [comment]
![AA1EB80A-99E3-4B01-970C-90B3EFAA26F3](https://user-images.githubusercontent.com/59745311/72198900-cc5fde00-3434-11ea-8f16-6c4ce891069f.png)

**Comment by fancythedeveloper** [comment]
Change GFX.ini maybe.

**Comment by OatmealDome** [comment]
@theomajeed This is how Nintendo intended the game to run (at 4:3), so Dolphin is correct.

If you *really* want it to fill the entire screen and have everything stretched, open ``/var/mobile/Documents/DolphiniOS/Config/GFX.ini`` and put ``AspectRatio = 3`` under ``[Settings].``
