### ISSUE TITLE
Need For Speed Carbon Crash on race startup

### ISSUE THREAD

**Issue by nfsvsgta** [OatmealDome/DolphiniOS-Issue-Tracker#27]
**Describe
On startup of the race, this error comes (see image) after which game hangs up.

**How to reproduce

Start any race

**Expected result**
Game crashed

**Device information**
 - Device iPhone XS Max
 - OS [e.g. iOS 12.2.1]
 - Jailbreak [e.g. uncover]
 - DolphiniOS version (go to the Settings tab) [e.g. v1.2.1
![7178A62B-E81F-48A3-8C0D-D7523D11342A](https://user-images.githubusercontent.com/19260668/72336403-bcdbd180-368e-11ea-8baa-e90513594c8a.png)
]

**Additional information**
Add any other information here that does not fit into the above sections.

**Comment by OatmealDome** [comment]
[This is a known issue with the Android version of Dolphin as well](https://forums.dolphin-emu.org/Thread-need-for-speed-carbon-crash). If you can, reproduce this issue on Android and file a bug report on the [official Dolphin issue tracker](https://bugs.dolphin-emu.org/).

You may be able to fix it by editing `/var/mobile/Documents/DolphiniOS/Config/Dolphin.ini`. Change ``JitBranchOff = False`` at the bottom of the file to ``JitBranchOff = True``. When you want to play another game, change it back to ``False`` to avoid performance loss.
