### ISSUE TITLE
Springboard crash when opening DolphiniOS while 3D Touch menu is open

### ISSUE THREAD

**Issue by Witherking25** [OatmealDome/DolphiniOS-Issue-Tracker#28]
**Describe the issue**
My springboard crashes when I open DolphiniOS while the 3D Touch menu is open

**How to reproduce**

1. Long press on DolphiniOS to open the 3D Touch menu
2. Tap on the app icon with the menu open
3. Springboard crashes

**Expected result**

the menu closing then opening the app

**Device information**
 - Device iPhone 7
 - OS iOS 13.1.2
 - Jailbreak checkra1n
 - DolphiniOS version v2.0.2

**Additional information**
Add any other information here that does not fit into the above sections.
https://pastebin.com/5r1GaXcn

**Comment by ckosmic** [comment]
Are you sure it’s not just a tweak causing it?  Mine opens as expected while jailbroken.  Try going into safe mode and reproducing to test it.

**Comment by Witherking25** [comment]
You are right. In safe mode it doesn’t happen
