### ISSUE TITLE
Will there be support CPU core 6

### ISSUE THREAD

**Issue by VoveGGG** [OatmealDome/DolphiniOS-Issue-Tracker#29]
Hi. I am very happy to use your app!!! As I understand it now, the maximum number of cores that can be used for emulating games is 4. Will support for more cores be added in the future? for newer Iphone models?

**Device information**
 - Device [e.g. iPhone 8]
 - OS [e.g. iOS 12.2]
 - Jailbreak [e.g. unc0ver]
 - DolphiniOS version (go to the Settings tab) [e.g. v2.0.0(233) petreon]

**Additional information**
Add any other information here that does not fit into the above sections.

**Comment by OatmealDome** [comment]
If you're referring to tutorials telling you to change `CPUCore` in `Dolphin.ini` to the number of cores your CPU has, then they are wrong. `CPUCore` is the type of emulator used for the GC/Wii CPU, not the number of cores on your CPU. Changing it to any value except the default may result in *much* slower performance.

Dolphin will never use more than 2 or 3 cores maximum, and adding more cores won't increase performance. Please read the following on the Dolphin project's website for more information: https://dolphin-emu.org/docs/faq/#couldnt-dolphin-use-more-my-cpu-cores-go-faster
