### ISSUE TITLE
Games not showing up.

### ISSUE THREAD

**Issue by aeth3rr** [OatmealDome/DolphiniOS-Issue-Tracker#3]
**Describe the issue**
Games do not show when placed in Software folder in Filza. If imported through Files app, the game shows up within the app, but in Filza.

**How to reproduce**
1. Import games into Software folder
2. Refresh app, no games.
3.Import games through the Files app, games show up.
4. Reopen Software folder, no games present.

**Expected result**
Expected Result: Games show up when placed in Software folder, games show up in Software folder when imported through Files

**Device information**
 - iPhone X
 - 13.2.3
 - checkra1n
 - v.1.0.6

**Additional information**
Add any other information here that does not fit into the above sections.

**Comment by CharlieWhile13** [comment]
What format is the game in?

**Comment by fancythedeveloper** [comment]
Format is important.
Make sure the format of the image is ISO, WBFS, CISO, GCZ, and some other formats.

**Comment by OatmealDome** [comment]
From what I remember of the conversation on Discord, this maybe due to combination of bad permissions (fixed in 1.0.x)?
