### ISSUE TITLE
Gamepad disabled after going back to menu or overlay screen with setting and close

### ISSUE THREAD

**Issue by thealgorithmc64** [OatmealDome/DolphiniOS-Issue-Tracker#30]

**Comment by thealgorithmc64** [comment]
Tried with a few devices including the following

- Mad CatZ MFI Bluetooth controller
- GV157A Gamevice controller (direct lightning connection

When initially running dolphinios, the controller works,  however when going to the overlay screen (swiping down) or/and running another game, the controller gets disabled.
Only rectification is to close dolphinios completely and run it again

- Made sure controller always connected option is enabled in options.
- Attempted to toggle between touchscreen and gamepad
- uninstalled ncontrol just incase there may be conflicts


Running on iPhone X with ios 13.3 and checkra1n jailbreak.

**Comment by guidogoyabeans** [comment]
It has been annoying to first deal with this after not saving, what made it work for me was disconnecting the controller and reconnecting it via Bluetooth (PS4 DualShock)

**Comment by OatmealDome** [comment]
Fixed in 2.1.0 (I believe).
