### ISSUE TITLE
Full screen/stretched option for iPhone X 

### ISSUE THREAD

**Issue by riqbal007** [OatmealDome/DolphiniOS-Issue-Tracker#35]
Hi, I was wondering if you able to add a full screen or stretch option for IPhone X

**Comment by OatmealDome** [comment]
Currently working on this. Awaiting Patreon version release.

**Comment by OatmealDome** [comment]
Added in 2.1.0 (Settings -> Graphics -> General(?) -> Aspect Ratio -> Stretch to Window).
