### ISSUE TITLE
Bug- 120fps game runs at capped 60fps

### ISSUE THREAD

**Issue by brand175** [OatmealDome/DolphiniOS-Issue-Tracker#38]
**Describe the issue**
Peter Jacksons King Kong The Video Game is supposed to run at 120fps but it caps to 60fps. The game is running 1/2 the speed except for the video cutscene's which runs at 60fps.

**How to reproduce**
Boot game on PC and iOS and look at the FPS meter on both devices on the language select screen.

**Expected result**
Game runs at half the speed.

**Device information**
 - Device [iPhone XR]
 - OS [iOS 12.4]
 - Jailbreak [Uncover 3.0.8 b1]
 - DolphiniOS version [v2.0.2 Public Release]

**Additional information**
Using the multitasking bar method makes the game run at normal speeds even if the Emulation Speed is set to 1. This issue is also related to the capped 120fps speed trick.

**Comment by OatmealDome** [comment]
Seems to be an issue on Android too. If you have an Android device, please reproduce and report to the [official bug tracker](https://bugs.dolphin-emu.org).

https://www.youtube.com/watch?v=wkyzqUnKtUo
