### ISSUE TITLE
Add quick save and load option 

### ISSUE THREAD

**Issue by riqbal007** [OatmealDome/DolphiniOS-Issue-Tracker#39]
Hi, 

Can you also add a quick save and load option just like in android version.

Thankyou

**Comment by Simonx22** [comment]
Do you mean save states? If yes, that feature will come in 2.1.0.

**Comment by riqbal007** [comment]
Yes, but do you know when you guys going to release her 2.1?

**Comment by OatmealDome** [comment]
We do not know at this time.

**Comment by OatmealDome** [comment]
Released.
