### ISSUE TITLE
Button remapping / resizing 

### ISSUE THREAD

**Issue by FuzzyNutz** [OatmealDome/DolphiniOS-Issue-Tracker#41]
Would be great if we could be able to move the wii emulated controller buttons where ever we want and resize them that way we could use mechanical controllers like the ones used for games like pubg mobile 
![3A35FBDF-4F98-4677-A9D2-BCC02FA62FD9](https://user-images.githubusercontent.com/26355018/75304683-e6515680-5811-11ea-9870-27314490397a.jpeg)

**Comment by OatmealDome** [comment]
Going to close as duplicate of #36 so we have one issue tracking all types of "controller editing".
