### ISSUE TITLE
Allow Moving/Resizing On-Screen Touch Controls

### ISSUE THREAD

**Issue by PkmnTrnrGary** [OatmealDome/DolphiniOS-Issue-Tracker#43]
Would love to see a feature added for moving/resizing touch controls. Not all hands are the same, so being able to customize those on-screen controls is a huge help to many people. Thanks!

**Comment by FuzzyNutz** [comment]
I just made this request yesterday

**Comment by OatmealDome** [comment]
Going to close as duplicate of #36 so we have one issue tracking all types of "controller editing".
