### ISSUE TITLE
Resolution Options

### ISSUE THREAD

**Issue by Crispy-99** [OatmealDome/DolphiniOS-Issue-Tracker#44]
Resolution changes for frames.
 - Device [iPhone 6s]
 - OS [iOS 13.2.3]
 - Jailbreak [unc0ver]
 -Dolphin Version [2.0.2]
I’ve seen resolution changes available for android versions, I’d like to see this added for iOS as well.

**Comment by OatmealDome** [comment]
Added in Patreon version 2.1.0. No ETA to public release, still fixing bugs.
