### ISSUE TITLE
XBOX ELITE 2 support

### ISSUE THREAD

**Issue by dr4c4h** [OatmealDome/DolphiniOS-Issue-Tracker#45]
I would like support for the xbox elite 2 controller. The controller pairs just fine with nControl but it does not show up in the controller section when in dolphinios like the normal xbox one controllers do. 

**Device information**
 - Device iPhone XR
 - OS 12.1.2
 - Jailbreak Chimera
 - DolphiniOS version v2.0.0

**Comment by OatmealDome** [comment]
Check other iOS games / emulators which support controllers and see if this Xbox Elite controller works with them. If they do, try restarting Dolphin while the controller is listed as connected in nControl.

**Comment by dr4c4h** [comment]
It does not work in other apps and restarting dolphinios did not fix the issue. This might be an issue with ncontrol, and not dolphinios I am also realizing. The xbox elite controller 2 also does not work on ios 13, even though it should. It could also be that xbox needs to push an update on the controller.

**Comment by OatmealDome** [comment]
Since this doesn't seem to be a Dolphin issue, I'm closing this. Try contacting nControl's developers.
