### ISSUE TITLE
Sonic unleashed 

### ISSUE THREAD

**Issue by SH1VEN80R** [OatmealDome/DolphiniOS-Issue-Tracker#47]
When you open sonic unleashed its all fine but lots of sprites don’t load.

For example on the main menu the hole screen is black after you beat the first tutorial level the game just freezes

I expected The game to work properly 

**Device information**
 - Device [iPhone 7]
 - OS [e.g. iOS 13.3]
 - Jailbreak [e.g.unc0ver]
 - DolphiniOS version (v2.0.2)

**Comment by OatmealDome** [comment]
This issue is now being tracked at #94. Thank you for your report.
