### ISSUE TITLE
OpenGL Backend Setting Set To Wrong Variable

### ISSUE THREAD

**Issue by brand175** [OatmealDome/DolphiniOS-Issue-Tracker#48]
**Describe the issue**
Clicking OpenGL doesn't enable OpenGL.
When going to the Dolphin.ini it says GFXBackend = OpenGL and it actually supposed to be OGL.

**Device information**
 - Device [Any]
 - DolphiniOS version [v2.1.0 185]

**Comment by OatmealDome** [comment]
Fixed in next Patreon release.
