### ISSUE TITLE
Nunchuk analog stick does not work

### ISSUE THREAD

**Issue by OatmealDome** [OatmealDome/DolphiniOS-Issue-Tracker#5]
**Describe the issue**
If you touch the Nunchuk's stick, it won't move.

**How to reproduce**
1. Open a Wii game.
2. Try and use the stick.

**Expected result**
The stick moves.

**Device information**
 - All devices
 - All iOS
 - All jailbreaks
 - v1.0.6

**Additional information**
Filed on behalf of brand175.

**Comment by OatmealDome** [comment]
Fixed in 1.0.7.

**Comment by vinnu73** [comment]
Please add the option of manually enabling, disabling and changing controllers to the options !

**Comment by Simonx22** [comment]
@vinnu73 please open a sperate issue for that
