### ISSUE TITLE
Return to Game After Deleting Game (Bug)

### ISSUE THREAD

**Issue by brand175** [OatmealDome/DolphiniOS-Issue-Tracker#51]
**Describe the issue**
After closing DolphiniOS and deleting the game, the return to game notification pops up for the game that no longer exists.

**Device information**
 - Device [Any]
 - OS [Any]
 - Jailbreak [Any]
 - DolphiniOS version (go to the Settings tab) [v2.1.0 185]

**Additional information**
An "The current game [blank] has been deleted from DolphiniOS. Would you like to keep the savestate for later use [Yes or No]" would be nice or disregard the return to game message completely if the game isn't found.

**Comment by OatmealDome** [comment]
Fixed in next Patreon release. Please open a separate issue for the yes/no option, so I don't forget.
