### ISSUE TITLE
Sonic Colors Works, But Doesn’t have all GUI

### ISSUE THREAD

**Issue by BlueberryTheDog** [OatmealDome/DolphiniOS-Issue-Tracker#57]
![C8D70AFC-CE6A-49CF-89AF-57147ADBA747](https://user-images.githubusercontent.com/61326261/80524171-d27eb980-8954-11ea-909e-76e4ba258929.png)
Sonic Colors Works Perfectly, Except it shows a black screen every now and then & the GUI is totally invisible

**Comment by BlueberryTheDog** [comment]
It only happens on DolphiniOS, I’ve tried sonic colors on normal pc dolphin, it has the GUI

**Comment by OatmealDome** [comment]
Now tracking at #94. Thanks for your report.

**Comment by Solardragon-Droid** [comment]
Cool
