### ISSUE TITLE
Lag when spamming a button

### ISSUE THREAD

**Issue by Matteo-cpu** [OatmealDome/DolphiniOS-Issue-Tracker#6]
**Describe the issue**
When i spam a button press, the game starts lagging

**How to reproduce**
Open a game

For example: 
1. Wii Games
2. GC Games
3. Get into debt.

**Expected result**
Run with occasional stutter 

**Device information**
 - Device iPhone 7
 - OS 12.4
 - Jailbreak Unc0ver
 - DolphiniOS version 1.0.6

**Additional information**
I know that the game should run with occasional stutter, specially on a A10 processor, but the the main lag is caused by spamming key presses on the screen

**Comment by OatmealDome** [comment]
Should be fixed in 2.0.0.
