### ISSUE TITLE
"Enable Progressive Scan" Button Bug

### ISSUE THREAD

**Issue by brand175** [OatmealDome/DolphiniOS-Issue-Tracker#61]
**Describe the issue**
Progressive scan doesn't work at all. Turning it on causes it to go back it off when exiting a game

**How to reproduce**
Enable Progressive scan in settings, Open Game
Close game, look at the setting

**Device information**
 - Device [e.g. iPhone XR]
 - OS [e.g. iOS 13.4]
 - Jailbreak [e.g. None]
 - DolphiniOS version (go to the Settings tab) [e.g. v2.2.1]

**Additional information**
Is Progressive scan even on the ini files because I can't find it.

**Comment by OatmealDome** [comment]
Fixed internally, awaiting Patreon release
