### ISSUE TITLE
Changing Config file crashes DolphiniOS

### ISSUE THREAD

**Issue by brand175** [OatmealDome/DolphiniOS-Issue-Tracker#65]
**Describe the issue**
Changing Emulation Speed, SyncOnSkipIdle etc and then booting a game causes DolphiniOS to crash and revert settings.

**Device information**
 - Device [e.g. iPhone XR]
 - OS [e.g. iOS 13.4]
 - Jailbreak [e.g. None]
 - DolphiniOS version (go to the Settings tab) [e.g. v3.0.0]

**Additional information**
Changing settings and then closing DolphiniOS via multitasking to save settings bypasses the crashing.

**Comment by OatmealDome** [comment]
You should not be modifying the INI files while Dolphin is running / in the background. The same goes for PC Dolphin as well.
