### ISSUE TITLE
Loading custom textures

### ISSUE THREAD

**Issue by lindskogen** [OatmealDome/DolphiniOS-Issue-Tracker#66]
I would like to be able to load custom HD textures on a non-jailbroken device

**Comment by OatmealDome** [comment]
There is an option in the graphics settings (I believe under Advanced) to turn on custom textures.

The procedure for turning on custom textures is the same as the PC versions of Dolphin. [See here for more information](https://forums.dolphin-emu.org/Thread-how-to-install-texture-packs-custom-textures-info). The only difference is that the "Load/Textures" directory is in the Files app under "DolphiniOS".

**Comment by lindskogen** [comment]
I don't see this directory, do I just create it if it doesn't exist?
