### ISSUE TITLE
Include .wad filetypes in game list

### ISSUE THREAD

**Issue by ckosmic** [OatmealDome/DolphiniOS-Issue-Tracker#7]
As of version 1.0.6, .wad files default to being listed as a Wii game with no visible title.  I’m not sure if .wads contain a title in them to be extracted, but if not, the file name can be used instead.

**Device information**
 - Device iPhone X
 - OS e.g. iOS 13.2.3
 - Jailbreak checkra1n
 - DolphiniOS version 1.0.6

**Comment by OatmealDome** [comment]
Could you give an example of a game with no title? The ones I have (UNO, Internet Channel, YouTube) have titles.

**Comment by ckosmic** [comment]
The ones that I’ve tried so far are the System Menu and Mii Channel wads.  Here are some screenshots:
![BE75CA1A-6D84-4080-8E10-6D3341E7D1EF](https://user-images.githubusercontent.com/17561672/70953330-bb7ea100-201d-11ea-8c81-8900023ac2fd.jpeg)
![749D0966-F228-4D5D-9BEB-F8626F5C99E5](https://user-images.githubusercontent.com/17561672/70953332-bb7ea100-201d-11ea-84d9-807f73bd5145.jpeg)

**Comment by OatmealDome** [comment]
Fixed in Patreon release 1.1.0. Awaiting public release.

**Comment by OatmealDome** [comment]
Fixed in 1.1.0.
