### ISSUE TITLE
sonic unleashed doesn't work

### ISSUE THREAD

**Issue by woshihuixiong** [OatmealDome/DolphiniOS-Issue-Tracker#74]
When open sonic unleashed(.iso), the whole menu(screen) is black, then if pressing A bottom it will play the first cutscene, after that all screen turn into black(I can hear the main menu voice though, and it seems the controller works, but the whole screen is black), finally for some reason, it plays the first cutscene again and again.

**Device information**
 - Device iPad air 3 with ps4 controller
 - OS iOS 13.4.1
 - Jailbreak no jailbreak
 - DolphiniOS version 2.2.2(1)(NJB)

hope you can fix it soon~ thanks.

**Comment by OatmealDome** [comment]
Now tracking at #94. Thanks for your report.
