### ISSUE TITLE
The Last Story bug on clothes textures

### ISSUE THREAD

**Issue by ren-shin** [OatmealDome/DolphiniOS-Issue-Tracker#76]
**Describe the issue** 
Clothes textures are transparent/invisible on the DolphiniOS. From what I searched, it was corrected on the desktop/windows version.

**How to reproduce**
Just start a new game. 

**Device information**
 - iPhone X and iPad 2018
 - IOS 13.4.1
 - Non jailbroken
 - DolphiniOS version 2.2.2 (1) (NJB)
![A4A5B2E4-3C0E-4D8E-99DC-4E082671983F](https://user-images.githubusercontent.com/65258651/81751548-08a85700-9486-11ea-8210-1e56a142c9ec.png)

**Comment by OatmealDome** [comment]
[Ensure that Settings -> Graphics -> Hacks -> Store EFB Copies to Texture Only is turned off](https://wiki.dolphin-emu.org/index.php?title=The_Last_Story#Clothes_Textures_Missing).

**WARNING**: This option will decrease performance. Turn it on when not needed.
