### ISSUE TITLE
Wii Pointer issue

### ISSUE THREAD

**Issue by brand175** [OatmealDome/DolphiniOS-Issue-Tracker#8]
**Describe the issue**
Touching the Wii pointer causes the D-pad and Nunchuk stick to stop functioning until the user stops using the Wii pointer. Other buttons work fine with the Wii pointer. Using the D-pad or Nunchuk stick also makes the Wii pointer not work.

**How to reproduce**
Finger on screen, use other hand to tap the d-pad or nunchuk stick.

**Device information**
 - iPhone XR
 - 12.4
 - Unc0ver
 - 1.0.7

**Additional information**
Add any other information here that does not fit into the above sections.

**Comment by OatmealDome** [comment]
This is intended, so that the D-Pad and Nunchuk don't get moved accidentally while the pointer is being dragged. Same for the other way around.

**Comment by gAbitecress** [comment]
It’s there a solution yet.
