### ISSUE TITLE
Weird crashing and issues on iPad 6th Gen

### ISSUE THREAD

**Issue by Brhsoftco** [OatmealDome/DolphiniOS-Issue-Tracker#80]
**Describe the issue**
After attempting to run _multiple_ games, a persistent issue keeps arising. The below games seem to be causing a weird glitch/error/issue with Dolphin for iOS, where loading a game (usually a WBFS file/WAD file) may cause the app to randomly create a save state, then lock up the touch controls. You will know when it does this, because a yellow box appears at the top telling you that it has saved the state to a file.

When this happens, it becomes impossible to regain control of the emulated WiiMote touch controls, as they become unresponsive to any touch feedback. Strangely, moving the device activates the gyro sometimes and appears to move onscreen pointers. On another note, forcefully closing the app without halting the emulation causes the emulation sound to continue playing for 4-10s before iOS seems to halt it...

**Games that have caused the problem so far**
***Wii Titles***
|  Name  | Publisher | Title Key  |
|---|---|---|
| Wall-E | THQ | RWAE78 |
| MySims | Electronic Arts | RSIE69 |
| Planet 51 | Sega Europe | RGAP8P |
| Ratatouille | THQ | RLWE78 |

**How to reproduce**
As described above, loading games will cause this issue to occur. It may happen randomly, but most commonly will occur after the Wii Loading screens or during Main menus.

Some things to try:
1. Load a game from the list above
2. Allow the emulation to proceed through
3. Await any lockups that might occur

**Expected result**
The games should load without too much hassle, and I should be able to load them up without the touch controls locking up. If this happens, at least an error code and a forced emulation stop would be nice :)

**Device information**
| Parameter | Value |
|-|-|
| Device | iPad 6th Generation |
| OS | iPadOS 13.4.1 |
| Jailbreak | Non-jailbroken (AltStore IPA installation) |
| Dolphin iOS Version | 2.2.2 (1) (NJB) |

**Additional information**
It should be noted that Logs/dolphin.log is literally "zero KB" (size 0 bytes). There are no logs to submit unfortunately.

**Comment by OatmealDome** [comment]
Fixed in latest Patreon, public release soon.
