### ISSUE TITLE
Controller buttons are switched

### ISSUE THREAD

**Issue by SarKaa** [OatmealDome/DolphiniOS-Issue-Tracker#82]
**Describe the issue**
So I am using an 8Bitdo n30 pro 2 controller, and I have to map out the controls, because the normal mapping is for xbox

**Device information**
 - Device iphone 7 plus
 - OS iOS 13.4.1
 - Jailbreak checkra1n
 - DolphiniOS version the latest (don't have access to my phone right now)

**Additional information**
Great work, this is awesome, its just the one problem with button mapping

**Comment by OatmealDome** [comment]
Apple doesn't provide a way to detect whether the controller uses the Xbox layout, PS layout, or Nintendo layout, unfortunately.
