### ISSUE TITLE
Sound doesn't go thru phone speakers

### ISSUE THREAD

**Issue by TheNinjaKingOW** [OatmealDome/DolphiniOS-Issue-Tracker#83]
**Describe the issue**
No sound will be player thru the phone's speaker

**How to reproduce**
Start any game

**Expected result**
Should play sound

**Device information**
 - iPhone 6s
 -iOS 13.4.1
 - Non-Jail Break
 - DolphiniOS version v2.2.2 (1)

**Comment by OatmealDome** [comment]
Unsilence your phone with the switch on the left edge.

**Comment by Simonx22** [comment]
Feel free to reopen this issue if it still doesn't work.
