### ISSUE TITLE
Can we rename save states?

### ISSUE THREAD

**Issue by stuartsmith04** [OatmealDome/DolphiniOS-Issue-Tracker#89]
Hi there. So good to have games on iOS. 

Would be awesome to rename save states so I know which game they relate to. At the moment they are just called ‘Save State 1,2,3’ etc. So for example be great to rename ‘save state 1’ to ‘Mario Galaxy’.

**Comment by OatmealDome** [comment]
Each game has its own set of save states. So, if you start Mario Galaxy, save states 1, 2, 3, etc are all specific to Mario Galaxy.
