### ISSUE TITLE
Ability to change controllers manually

### ISSUE THREAD

**Issue by Simonx22** [OatmealDome/DolphiniOS-Issue-Tracker#9]
**Describe the feature you'd like**
Some games, for example, Mario Kart Wii, support a GameCube controller. A simple manual switch to use a GameCube controller in the settings would be nice.

**Comment by vinnu73** [comment]
Disabling and enabling them manually would also be helpful, please add this option.

**Comment by OatmealDome** [comment]
Fixed in 1.1.0.
