### ISSUE TITLE
Game save states immediately after loading, locking all inputs to app

### ISSUE THREAD

**Issue by JackFusion07** [OatmealDome/DolphiniOS-Issue-Tracker#91]
_I hope no one's done this one yet_

**Describe the issue**
When loading a game, the save state text appears immediately upon load, locking controls and the slide down menu and making the game unplayable requiring to close the app entirely. In my case, this was with Mario Kart Wii using Gamecube Slot 1. Edit 6/1: This appears to only happen when reopening the game manually following the "Continue Session" prompt. 

**How to reproduce**
1. Load a game with Emulated Gamecube Controller in Slot 1 (in my case Mario Kart Wii)
Edit 6/1:
2. Close the game anytime during gameplay
3. Reopen DolphinIOS and close the "Continue Session" prompt
4. Reopen the game manually

**Expected result**
The game in any normal case should allow inputs and should not save state immediately after loading.

**Device information**
 - iPhone 7
 - iOS 13.3.1
 - Jailbroken with checkra1n
 - Patreon 3.0.0 (193), _maybe_ 2.2.3 (4)

**Additional information**
It should be noted that I've had this happen to me several times, though I've never gotten it to manually trigger and it does not happen often. This has resulted in my phone crashing at least once. If I can get footage of it happening, I will send it here. I'm not sure if this happens with Wiimote as the emulated controller.

**Comment by JackFusion07** [comment]
I have got it to happen again. It seems this happens when reopening the app, getting the continue message, closing it and reopening the game. I'll reflect this on the original bug report, but here's a link to the video I recorded of it happening: https://youtu.be/s89igHswlMc

**Comment by OatmealDome** [comment]
Fixed in latest Patreon, public release soon.
