### ISSUE TITLE
Graphical glitch in Kirby air ride

### ISSUE THREAD

**Issue by milesssx** [OatmealDome/DolphiniOS-Issue-Tracker#92]
**Describe the issue**
I hope this is the right place to do this.
Ive had no issues with DolphiniOS so far, it has worked perfectly. But when i try to play Kirby air ride everything is fin until the gameplay starts and the majority of the graphics are all black. Some textures will load but the game is unplayable. I’ve messed around with settings to no avail 

**How to reproduce**
I have downloaded two different ISO files for Kirby air ride and both times the graphics have not cooperated so if you try it out I’m sure it will reproduce
**Device information**
 - Device IPad Pro 2020
 - OS [e.g. iOS 13.41
 - Jailbreak nope
 - DolphiniOS version 2.2.2 (1) NJB

Sorry for the low image quality, couldn’t figure out how to attach this other than a bad GIF conversion 
![Image](https://user-images.githubusercontent.com/66348456/83596363-15bae200-a52a-11ea-95fa-9582ecfcb680.gif)

**Comment by JackFusion07** [comment]
Please see this reply from an older issue:

> Metal doesn't expose LogicOps support, which Kirby's Air Ride uses heavily, causing the incorrect rendering. This also affects macOS when using Vulkan over MoltenVK.
> 
> The only way to fix this issue is to get Apple to add public LogicOps support to Metal. It's literally already there, but they're not exposing it to developers.
> 
> MoltenVK is tracking this bug at [KhronosGroup/MoltenVK#374](https://github.com/KhronosGroup/MoltenVK/issues/374).

**Comment by milesssx** [comment]
Thanks!

**Comment by OatmealDome** [comment]
Now tracking at #95. Thanks for the report.
